name: Build TWRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP Recovery with Provided Device Info
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set Swap Space (Optional)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Build TWRP
      uses: mlm-games/TWRP-recovery-build-action@v1.1
      with:
        MANIFEST_BRANCH: 'twrp-12.1'
        DEVICE_TREE: 'https://github.com/GrenJIkxd/android_device_samsung_gts8'
        DEVICE_TREE_BRANCH: 'main'
        DEVICE_NAME: ''
        DEVICE_PATH: ''
        MAKEFILE_NAME: ''
        BUILD_TARGET: 'boot'

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Recovery
        path: ${{ env.OUTPUT_DIR }}/*.img
